### ISSUE TITLE
Decide on hardware and interface for heart rate monitoring

### ISSUE THREAD

**Issue by Graeme22** [Graeme22/adrenaline#2]
The original plan of using Fitbit may not be viable. The Fitbit communications model REQUIRES that all communication is done first through the phone, adding latency and overhead we probably don't want.

So, we should be looking at alternative ways to monitor heart rate in real time. That means other watch brands:
- [x] Garmin
- [x] Apple watch

as well as, potentially, a non-watch solution:

- [ ] Arduino microcontroller
- [x] Webcam-based monitor

Any suggestions are welcome.

**Comment by Graeme22** [comment]
I should add that fitbit is feasible. It's just a bit of a pain. So we could still settle on it as well.

**Comment by Graeme22** [comment]
We will stick with fitbit for now. Communications will have a bit of latency and there's some extra coding required, but it's doable.

**Comment by Mike-charlie** [comment]
I strongly believe the best way to make this project the most accessible to every user is to use smart watches, apparently over 20% of adults in america own smart watches of some sort and 50% of them are Apple watches with 12.2% being FitBit and 11.8% being Samsung watches. Part of the issue may be finding contributors who have the watches. 

It may be useful to create a document where we can check off what watches we have access to for testing. Myself I have a Samsung watch so if someone has an Apple watch and a third has a FitBit we should be able to get access to 74% of smart watch owners. 

With the above numbers it suggests we will be able to reach 74% of the 20% of adult Americans. According to the 2000 Census there are 209 million American adults. This means there are an estimated 41.8 million watch users in America and we would be able to have it work with 31 million of them. This feels like the best way to get to the most people as alot of people will not want to mess with Arduinos and electronics if they could help it. And as for webcam monitoring I believe it would be possible but would be a lot more difficult.
